using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;
using HtmlAgilityPack;
using iTextSharp;
using iTextSharp.text;
using iTextSharp.text.pdf;

namespace Prawnotron
{


    /// <summary>
    ///
    /// </summary>
    /// <autogeneratedoc />
    public class Statue
    {
        HtmlDocument HtmlFromFile { get; }
        public List<string> Pages { get; }

        /// <summary>
        /// Konstruktor
        /// </summary>
        /// <autogeneratedoc />
        /// <param name="a"></param>
        /// <param name="readFromString"></param>
        public Statue(string a, bool readFromString = false)
        {
            Pages = new List<string>();
            HtmlDocument html = readFromString ? ReadHtmlDocumentFromString(a) : ReadHtmlDocumentFromFile(a);
            HtmlFromFile = html;
            ReadStatuePagesFromHtml(HtmlFromFile); //przerabia html na strony
        }

        private void ReadStatuePagesFromHtml(HtmlDocument document)
        {
            HtmlNodeCollection htmlNodes = document.DocumentNode.SelectNodes("(//div[@class='pf w0 h0'])");
                //wybieramy wszystkie 'div' o takiej samej klasie
            // XPATH: http://ricostacruz.com/cheatsheets/xpath.html
            foreach (var node in htmlNodes)
            {
                string pageContent = "";
                HtmlNodeCollection pageElements = node.SelectNodes("(div/div[position()>2])");
                foreach (var element in pageElements)
                {
                    if (element.InnerText != "")
                        //jezeli innerText nie jest pusty - (dokument zawiera duzo pustych spanów)
                    {
                        pageContent += element.InnerText; //dodaje tekst do zawartosci strony
                    }
                }

                Pages.Add(pageContent); //strona dodana do listy stron
            }
        }

        private static HtmlDocument ReadHtmlDocumentFromFile(string documentPath)
        {
            HtmlDocument doc = new HtmlDocument();
            doc.Load(documentPath, Encoding.UTF8);
            return doc;
        }

        private HtmlDocument ReadHtmlDocumentFromString(string html)
        {
            HtmlDocument doc = new HtmlDocument();
            doc.LoadHtml(html);
            return doc;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();

            foreach (var page in Pages)
            {
                sb.Append(page);
            }

            return sb.ToString();
        }

        /// <summary>
        /// 
        /// </summary>
      
        /// <summary>
        /// 
        /// </summary>
        /// <param name="doc"></param>
        /// <param name="a"></param>
          public string Wyszukaj(string doc, string a)
        {
            var list = new List<string>();
            string trescArt ="";
            string pattern = "Art. " + a;  //tworzymy wzor1 który chcemy wyszukac w tekscie na przykład : "Art. 44"
            var index = 0;              
            int num1 = int.Parse(a);        //parsujemy podany nr artykulu w stringu na int, żeby dało sie go zwiekszyc o 1 i wykorzystac we wzorze2 (końcowym)
            int num2 = num1 + 1;            //tworzymy numer artykulu nastepnego, którego juz ma nie wyciagac
            string d = Convert.ToString(num2);  //numer artykulu konwertujemy na string by utworzyc wzor2 koncowy
            string pattern2 = "Art. " + d;
            while (true)

            {
                int b = doc.IndexOf(pattern, index, StringComparison.Ordinal);//szukamy indexu wzoru1 w tekscie
                if (b == -1)
                    break;
                index = b + pattern.Length;

                int c = doc.IndexOf(pattern2, index, StringComparison.Ordinal);//szukamy indexu wzoru2 w tekscie

                list.Add(pattern + doc.Substring(index, c - index)); //dodajemy do listy fragment tekstu zawieracy wzor1 wraz z tekstem artykulu czyli np "Art. 44 blabla." konczący sie gdy napotka sie wzor2 czyli "Art. 45"
            }
            foreach (string line in list)
            {
                trescArt += line;
                Debug.WriteLine(line);  //tutaj juz testowalysmy jak dziala
            }
            return trescArt;
        }
        
            public void Zapisz(string textToSave)
            {

                FileStream fs = new FileStream("Artykuł.pdf", FileMode.Create, FileAccess.Write, FileShare.None);


                Document doc = new Document();

                PdfWriter writer = PdfWriter.GetInstance(doc, fs);

                doc.Open();

                doc.Add(new Paragraph(textToSave));

                doc.Close();
            }
     
        /*static void Main(string[] args)
                {
                    
                   Statue ustawa = new Statue("strona_3.html");
                    string p;
                    string ustawaString = "";
                        foreach (var page in ustawa.pages)
                    {
                        
                        p = Convert.ToString(page);
                        ustawaString+= p;
        
                    }
                
                    ustawaString=ustawa.Wyszukaj(ustawaString, "44");
            ustawa.Zapisz(ustawaString);
                 
        
                Console.ReadKey();
                }
            }*/
    }
}
