using System.Diagnostics.CodeAnalysis;
using System.IO;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Prawnotron
{
    /// <summary>
    ///     Model ustawy pobieranej z API
    /// </summary>
    /// <autogeneratedoc />
    [SuppressMessage("ReSharper", "UnusedAutoPropertyAccessor.Global")]
    public class Ustawa
    {
        /// <summary>
        ///     ID ustawy w API
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        ///     ID używane do pobrania treści ustawy
        /// </summary>
        public string DokumentId { get; set; }

        /// <summary>
        /// ID dokumentu w systemie ISAP
        /// </summary>
        public string IsapPlikDokumentId { get; set; }
        /// <summary>
        /// Gets or sets the isap identifier.
        /// </summary>
        /// <value>
        /// The isap identifier.
        /// </value>
        /// <autogeneratedoc />
        public string IsapId { get; set; }
        /// <summary>
        /// Gets or sets the status identifier.
        /// </summary>
        /// <value>
        /// The status identifier.
        /// </value>
        /// <autogeneratedoc />
        public string StatusId { get; set; }
        /// <summary>
        /// Gets or sets the rok.
        /// </summary>
        /// <value>
        /// The rok.
        /// </value>
        /// <autogeneratedoc />
        public string Rok { get; set; }
        /// <summary>
        /// Gets or sets the poz.
        /// </summary>
        /// <value>
        /// The poz.
        /// </value>
        /// <autogeneratedoc />
        public int Poz { get; set; }
        /// <summary>
        /// Gets or sets the nr.
        /// </summary>
        /// <value>
        /// The nr.
        /// </value>
        /// <autogeneratedoc />
        public int Nr { get; set; }
        /// <summary>
        /// Gets or sets the sygnatura.
        /// </summary>
        /// <value>
        /// The sygnatura.
        /// </value>
        /// <autogeneratedoc />
        public string Sygnatura { get; set; }
        /// <summary>
        /// Gets or sets the data publikacji.
        /// </summary>
        /// <value>
        /// The data publikacji.
        /// </value>
        /// <autogeneratedoc />
        public string DataPublikacji { get; set; }
        /// <summary>
        /// Gets or sets the data wydania.
        /// </summary>
        /// <value>
        /// The data wydania.
        /// </value>
        /// <autogeneratedoc />
        public string DataWydania { get; set; }
        /// <summary>
        /// Gets or sets the data wejscia w zycie.
        /// </summary>
        /// <value>
        /// The data wejscia w zycie.
        /// </value>
        /// <autogeneratedoc />
        public string DataWejsciaWZycie { get; set; }
        /// <summary>
        /// Gets or sets the label.
        /// </summary>
        /// <value>
        /// The label.
        /// </value>
        /// <autogeneratedoc />
        public string Label { get; set; }

        /// <summary>
        ///     Tytuł ustawy.
        /// </summary>
        public string Tytul { get; set; }

        /// <summary>
        ///     Tytuł skrócony ustawy.
        /// </summary>
        /// <autogeneratedoc />
        public string TytulSkrocony { get; set; }
        /// <summary>
        /// Gets or sets the autor nazwa.
        /// </summary>
        /// <value>
        /// The autor nazwa.
        /// </value>
        /// <autogeneratedoc />
        public string AutorNazwa { get; set; }
        /// <summary>
        /// Gets or sets the zrodlo.
        /// </summary>
        /// <value>
        /// The zrodlo.
        /// </value>
        /// <autogeneratedoc />
        public string Zrodlo { get; set; }

        /// <summary>
        /// Gets or sets the kodeks.
        /// </summary>
        /// <value>
        /// The kodeks.
        /// </value>
        /// <autogeneratedoc />
        public string Kodeks { get; set; }
        /// <summary>
        /// Gets or sets the liczba zalacznikow.
        /// </summary>
        /// <value>
        /// The liczba zalacznikow.
        /// </value>
        /// <autogeneratedoc />
        public int LiczbaZalacznikow { get; set; }
        /// <summary>
        /// Gets or sets the typ nazwa.
        /// </summary>
        /// <value>
        /// The typ nazwa.
        /// </value>
        /// <autogeneratedoc />
        public string TypNazwa { get; set; }

        /// <summary>
        ///     Metoda usuwająca nazwę datasetu z parametrów we wskazanym pliku <c>JSON</c>
        /// </summary>
        /// <param name="jsonPath">ścieżka do pliku <c>JSON</c></param>
        /// <seealso cref="File" />
        /// <param name="dataset">nazwa datasetu z API, np. prawo, dziennik_ustaw. Domyślnie "dziennik_ustaw"</param>
        static void RemoveDatasetName(string jsonPath, string dataset = "dziennik_ustaw.")
        {
            string text = File.ReadAllText(jsonPath);
            text = text.Replace(dataset, "");
            File.WriteAllText(jsonPath, text);
        }

        /// <summary>
        ///     Deserialuje pliki <c>JSON</c> do klasy Ustawa <see cref="Ustawa" />, korzystając z zamiany na
        /// </summary>
        /// <param name="id">ścieżka do pliku <c>JSON</c> <seealso cref="int" /></param>
        /// <returns>Deserializowany obiekt klasy Ustawa</returns>
        static void ParseUstawa(int id)
        {
            string p = $"../../Json/Ustawa_{id}.json";
            RemoveDatasetName(p);

            string ustStr = File.ReadAllText(p);

            JObject mpResult = JObject.Parse(ustStr);
            JToken result = mpResult["data"];

            JsonConvert.DeserializeObject<Ustawa>(result.ToString());
        }

        /// <summary>
        ///     Konstruktor klasy Ustawa, deserializujący z pliku JSON.
        ///     <seealso cref="ParseUstawa" />
        /// </summary>
        /// <param name="id">nazwa pliku JSON z danymi o ustawie</param>
        public Ustawa(int id)
        {
            ParseUstawa(id);
        }
    }
 }
