namespace Prawnotron
{

    /// <summary>
    /// Model ustawy pobieranej z API
    /// </summary>
    /// <autogeneratedoc />
    public class Ustawa {
        /// <summary>
        /// ID ustawy w API
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// ID używane do pobrania treści ustawy
        /// </summary>
        public string DokumentId { get; set; }

        public string IsapPlikDokumentId { get; set; }
        public string IsapId { get; set; }
        public string StatusId { get; set; }

        public int Rok { get; set; }
        public int Poz { get; set; }
        public int Nr { get; set; }
        public string Sygnatura { get; set; }

        public string DataPublikacji { get; set; }
        public string DataWydania { get; set; }
        public string DataWejsciaWZycie { get; set; }

        public string Label { get; set; }
        public string Tytul { get; set; }
        public string TytulSkrocony { get; set; }
        public string AutorNazwa { get; set; }
        public string Zrodlo { get; set; }


        public string Kodeks { get; set; }
        public int LiczbaZalacznikow { get; set; }
        public string TypNazwa { get; set; }


    }
 }
